-- MySQL Script generated by MySQL Workbench
-- 08/27/20 20:03:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projeto_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_java` DEFAULT CHARACTER SET utf8 ;
USE `projeto_java` ;

-- -----------------------------------------------------
-- Table `projeto_java`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_java`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `link` VARCHAR(100) NOT NULL,
  `icone` VARCHAR(45) NULL,
  `exibir` INT NOT NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_java`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_java`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_java`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_java`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `login` VARCHAR(10) NOT NULL,
  `senha` VARCHAR(10) NOT NULL,
  `status` INT NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_perfil1_idx` (`perfil_idperfil` ASC),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `projeto_java`.`perfil` (`idperfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto_java`.`menu_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_java`.`menu_perfil` (
  `menu_idmenu` INT NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`menu_idmenu`, `perfil_idperfil`),
  INDEX `fk_menu_has_perfil_perfil1_idx` (`perfil_idperfil` ASC),
  INDEX `fk_menu_has_perfil_menu_idx` (`menu_idmenu` ASC),
  CONSTRAINT `fk_menu_has_perfil_menu`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `projeto_java`.`menu` (`idmenu`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_menu_has_perfil_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `projeto_java`.`perfil` (`idperfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
